import Head from 'next/head'
export default function Header(props: { title: string, children?: string }) {
    return (
        <div>
            <Head>
                <title>Portal Noticias {props.title ? `| ${props.title}` : ""}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <div>{props.children}</div> */}
        </div>
    )

}